import { useState } from "react";
import { useLocation } from "wouter";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowLeft, BarChart3, TrendingUp, GraduationCap, BrainCircuit,
  Users, Building2, Stethoscope, ChevronRight, ShieldCheck,
  ClipboardList, FileText, Lock, AlertTriangle, Bot, Globe, Briefcase, Zap,
  FolderOpen, Star, Brain, BookOpen,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth";
import { useQuery } from "@tanstack/react-query";
import { LEADERSHIP_LABELS } from "@shared/schema";
import { useFacilityFeatures, isEnabled } from "@/lib/features";
import type { FacilityFeatures } from "@/lib/features";

const LEADERSHIP_RANK: Record<string, number> = {
  learner: 0, educator: 1, director: 2, ceo: 3, admin: 4, super_admin: 5,
};

function getEffectiveRole(user: { isAdmin: boolean; leadershipRole?: string | null }) {
  const lr = (user.leadershipRole as string) || "learner";
  if (user.isAdmin && (LEADERSHIP_RANK[lr] ?? 0) < LEADERSHIP_RANK["admin"]) return "admin";
  return lr;
}

interface ConsoleCard {
  id: string;
  title: string;
  description: string;
  icon: React.ElementType;
  iconBg: string;
  iconColor: string;
  href: string;
  minRole: string;
  badge?: string;
  featureKey?: keyof FacilityFeatures;
  ascOnly?: boolean;
}

function getConsoleCards(activeStandardsBody: string): ConsoleCard[] { return [
  {
    id: "hospital-dashboard",
    title: "Hospital Learning Dashboard",
    description: "Staff knowledge score, learning journey progress, department breakdown, and individual status — all in one view. Updated in real time from quiz and assessment data.",
    icon: BarChart3,
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-600",
    href: "/hospital-dashboard",
    minRole: "director",
    badge: "Live",
    featureKey: "show_hospital_dashboard",
  },
  {
    id: "asc-dashboard",
    title: "ASC Executive Dashboard",
    description: "Survey readiness score, AAAHC policy review status, staff training completion by track, and compliance alerts — purpose-built for ambulatory surgery centers.",
    icon: Stethoscope,
    iconBg: "bg-teal-500/10",
    iconColor: "text-teal-600",
    href: "/asc-dashboard",
    minRole: "director",
    badge: "Live",
    featureKey: "show_asc_dashboard",
    ascOnly: true,
  },
  {
    id: "survey-readiness",
    title: "Survey Readiness Agent",
    description: `Live compliance score across all ${activeStandardsBody} standards, color-coded by surveyor risk. Green above 90%, amber 75–90%, red below 75%.`,
    icon: ShieldCheck,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-600",
    href: "/survey-readiness",
    minRole: "director",
    badge: "Live",
    featureKey: "survey_readiness_agent",
  },
  {
    id: "content-intelligence",
    title: "Content Intelligence Agent",
    description: `Upload a policy document and AI reads it, tags ${activeStandardsBody} standards, generates quiz questions, flags conflicts, and creates a mini-training module ready for one-click approval.`,
    icon: Bot,
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-600",
    href: "/content-intelligence",
    minRole: "director",
    badge: "AI",
    featureKey: "content_intelligence_agent",
  },
  {
    id: "compliance-tasks",
    title: "Compliance Task Manager",
    description: "View, assign, and track all compliance tasks by status. Create new tasks manually or review tasks generated by the AI agents.",
    icon: ClipboardList,
    iconBg: "bg-sky-500/10",
    iconColor: "text-sky-600",
    href: "/compliance-tasks",
    minRole: "director",
    badge: "Tool",
    featureKey: "compliance_task_manager",
  },
  {
    id: "executive-brief",
    title: "Executive Readiness Agent",
    description: "Generates a weekly plain-English compliance brief for CEOs and CNOs. Combines readiness scores, overdue items, expiring documents, and staff training gaps into a one-page summary with trend direction. Delivers via email.",
    icon: Briefcase,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-600",
    href: "/executive-brief",
    minRole: "ceo",
    badge: "Agent",
    featureKey: "executive_readiness_agent",
  },
  {
    id: "regulatory-watch",
    title: "Regulatory Watch Agent",
    description: `Monitors ${activeStandardsBody} standards pages for updates and new requirements. Flags affected compliance items, creates review tasks, and alerts your compliance officer automatically.`,
    icon: Globe,
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-600",
    href: "/regulatory-watch",
    minRole: "director",
    badge: "Agent",
    featureKey: "regulatory_watch_agent",
  },
  {
    id: "staff-learning",
    title: "Staff Learning Agent",
    description: `Maps quiz completions to ${activeStandardsBody} compliance items. Identifies staff with training gaps and recommends targeted focus areas.`,
    icon: GraduationCap,
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-600",
    href: "/staff-learning",
    minRole: "director",
    badge: "Agent",
    featureKey: "show_staff_learning_agent",
  },
  {
    id: "executive-report",
    title: "Executive Readiness Report",
    description: "Facility-wide readiness scores, trend charts, and guided education plan status with CSV/PDF export.",
    icon: TrendingUp,
    iconBg: "bg-primary/10",
    iconColor: "text-primary",
    href: "/executive-report",
    minRole: "director",
    badge: "Exec",
  },
  {
    id: "teams",
    title: "Team Management",
    description: "Create named teams within your facility, add members, and track each team's training progress and streaks side-by-side.",
    icon: Users,
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-600",
    href: "/educator",
    minRole: "ceo",
    badge: "New",
    featureKey: "show_teams",
  },
  {
    id: "user-management",
    title: "User Management",
    description: "View all registered learners, track engagement and accuracy, and assign leadership roles.",
    icon: Users,
    iconBg: "bg-chart-2/10",
    iconColor: "text-chart-2",
    href: "/admin",
    minRole: "director",
  },
  {
    id: "guided-education",
    title: "Guided Education Oversight",
    description: "Monitor active guided education plans and track overdue assignments.",
    icon: GraduationCap,
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-600",
    href: "/corrective-actions",
    minRole: "director",
  },
  {
    id: "ai-coach",
    title: "AI Leadership Coach",
    description: "AI-generated readiness summaries, staff performance insights, and recommended focus areas.",
    icon: BrainCircuit,
    iconBg: "bg-chart-4/10",
    iconColor: "text-chart-4",
    href: "/admin",
    minRole: "director",
    badge: "AI",
  },

];}

export default function LeadershipHubPage() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const [onboardingDismissed, setOnboardingDismissed] = useState<boolean>(() => {
    try { return localStorage.getItem("ar_compliance_onboarding_done") === "1"; } catch { return false; }
  });

  const effectiveRole = user ? getEffectiveRole(user) : "learner";
  const effectiveRank = LEADERSHIP_RANK[effectiveRole] ?? 0;

  const isAsc = user?.organizationType === "asc";
  const isDnv = user?.organizationType === "dnv";
  const moduleLabel = isAsc ? "ASC" : isDnv ? "DNV" : "Hospital";
  const activeStandardsBody = isAsc ? "AAAHC" : isDnv ? "DNV NIAHO" : "Joint Commission";
  const ModuleIcon = isAsc ? Stethoscope : Building2;

  const leadershipLabel = user
    ? (LEADERSHIP_LABELS as Record<string, string>)[effectiveRole] ?? effectiveRole
    : "-";

  const canAccess = (card: ConsoleCard) =>
    effectiveRank >= (LEADERSHIP_RANK[card.minRole] ?? 99);

  const needsMfa = effectiveRank >= LEADERSHIP_RANK["ceo"];
  const { data: mfaStatus } = useQuery<{ required: boolean; enabled: boolean; verified: boolean }>({
    queryKey: ["/api/mfa/status"],
    enabled: needsMfa,
  });

  const { data: staffEngagement } = useQuery<import("@shared/schema").StaffEngagementEntry[]>({
    queryKey: ["/api/points/staff-engagement"],
    enabled: effectiveRank >= LEADERSHIP_RANK["director"],
  });

  const { data: facilitySettings, isLoading: settingsLoading } = useQuery<{ complianceMode: string }>({
    queryKey: ["/api/facility/settings"],
    enabled: !!user && effectiveRank >= LEADERSHIP_RANK["director"],
  });

  const { data: facilityFlags } = useFacilityFeatures();

  const complianceMode = facilitySettings?.complianceMode ?? "education_only";
  const showOnboardingBanner = !settingsLoading && complianceMode !== "full_platform" && !onboardingDismissed && effectiveRank >= LEADERSHIP_RANK["director"];

  function dismissOnboarding(enableFull: boolean) {
    try { localStorage.setItem("ar_compliance_onboarding_done", "1"); } catch {}
    setOnboardingDismissed(true);
    if (enableFull) {
      fetch("/api/admin/facility/compliance-mode", {
        method: "PATCH",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ complianceMode: "full_platform" }),
      });
    }
  }

  return (
    <div className="min-h-screen pb-20">
      {/* Sub-header */}
      <div className="sticky top-[58px] z-40 border-b border-border bg-background/95 backdrop-blur-md">
        <div className="max-w-5xl mx-auto px-6 py-3 flex items-center gap-3">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setLocation("/dashboard")}
            data-testid="button-back-to-training"
            aria-label="Back to training"
          >
            <ArrowLeft size={20} />
          </Button>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <h1 className="font-bold text-base text-foreground">Leadership Console</h1>
              <span
                className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-bold bg-primary/10 text-primary border border-primary/20"
                data-testid="badge-module-scope"
              >
                <ModuleIcon size={11} />
                {moduleLabel}
              </span>
            </div>
            <p className="text-sm font-medium text-foreground/70" data-testid="text-role-label">
              {leadershipLabel} · facility-scoped view
            </p>
          </div>
          <div className="flex items-center gap-1.5 flex-shrink-0">
            <ShieldCheck size={14} className="text-primary" />
            <span className="text-xs font-semibold text-primary hidden sm:inline">Secured</span>
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="max-w-5xl mx-auto px-6 pt-8 flex flex-col gap-8">

        {/* MFA setup banner for ceo+ users */}
        {needsMfa && mfaStatus && !mfaStatus.enabled && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border-2 border-orange-500/60 bg-orange-50 dark:bg-orange-500/15 p-5 flex items-start gap-4"
            data-testid="banner-mfa-setup"
          >
            <div className="w-10 h-10 rounded-xl bg-orange-500/20 flex items-center justify-center flex-shrink-0">
              <AlertTriangle size={20} className="text-orange-600 dark:text-orange-400" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="font-bold text-sm mb-1 text-foreground">Two-Factor Authentication Required</h2>
              <p className="text-sm text-foreground/80 leading-relaxed mb-3">
                Your role requires MFA to access reporting tools. Set up your authenticator app now to unlock the Executive Report, AI Coach, and data exports.
              </p>
              <Button size="sm" onClick={() => setLocation("/mfa-setup")} data-testid="button-setup-mfa-from-hub">
                Set Up MFA Now
              </Button>
            </div>
          </motion.div>
        )}

        {/* MFA verify banner - set up but not verified this session */}
        {needsMfa && mfaStatus?.enabled && !mfaStatus.verified && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border-2 border-primary/50 bg-primary/8 p-5 flex items-start gap-4"
            data-testid="banner-mfa-verify"
          >
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
              <ShieldCheck size={20} className="text-primary" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="font-bold text-sm mb-1">Verify Your Identity</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-3">
                Enter your authenticator code to access reporting tools for this session.
              </p>
              <Button size="sm" onClick={() => setLocation("/mfa-verify")} data-testid="button-verify-mfa-from-hub">
                Enter Code
              </Button>
            </div>
          </motion.div>
        )}

        {/* Scope banner */}
        {effectiveRole === "super_admin" && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-border bg-card p-5 flex items-start gap-4"
            data-testid="card-scope-info"
          >
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
              <BarChart3 size={20} className="text-primary" />
            </div>
            <div className="min-w-0">
              <h2 className="font-bold text-sm mb-1">Your data scope</h2>
              <p className="text-sm text-muted-foreground leading-relaxed" data-testid="text-scope-description">
                You have platform-wide access. All facilities and modules are visible.
              </p>
            </div>
          </motion.div>
        )}

        {/* Facility scoping note for hospital/ASC separation */}
        {effectiveRole === "super_admin" && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-xl border border-orange-500/50 bg-orange-50 dark:bg-orange-500/10 px-4 py-3 flex items-center gap-2 text-sm text-foreground/80"
            data-testid="banner-multi-module"
          >
            <ClipboardList size={15} className="flex-shrink-0 text-orange-500" />
            <span>
              <strong>Multi-module admin:</strong> Hospital and ASC data are segregated. Use the pathway switcher on the learner dashboard to change your active module context.
            </span>
          </motion.div>
        )}

        {/* Compliance onboarding banner */}
        {showOnboardingBanner && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border-2 border-primary/50 bg-primary/5 p-5 flex items-start gap-4"
            data-testid="banner-compliance-onboarding"
          >
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
              <Zap size={20} className="text-primary" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="font-bold text-sm mb-1">Set up compliance management</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                Would you like to enable the full compliance management suite? This includes the Survey Readiness Agent, Compliance Task Manager, Regulatory Watch, and AI compliance agents. You can change this any time in Facility Settings.
              </p>
              <div className="flex flex-wrap gap-2">
                <Button
                  size="sm"
                  onClick={() => dismissOnboarding(true)}
                  data-testid="button-onboarding-enable-full"
                >
                  Enable Full Platform
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => dismissOnboarding(false)}
                  data-testid="button-onboarding-keep-education"
                >
                  Education Only
                </Button>
              </div>
            </div>
          </motion.div>
        )}

        {/* Console cards */}
        <div>
          <h2 className="text-sm font-bold uppercase tracking-wider text-foreground/60 mb-4" data-testid="text-tools-label">
            Leadership Tools
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {getConsoleCards(activeStandardsBody).filter(card =>
              (!card.featureKey || isEnabled(facilityFlags?.features, card.featureKey)) &&
              (!card.ascOnly || isAsc)
            ).map((card, i) => {
              const accessible = canAccess(card);
              const Icon = card.icon;
              return (
                <motion.div
                  key={card.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.06 }}
                  data-testid={`card-console-${card.id}`}
                  className={`rounded-2xl border-2 p-5 flex flex-col gap-3 transition-all ${
                    accessible
                      ? "border-border bg-card hover:border-primary/40 hover:shadow-md cursor-pointer"
                      : "border-border/60 bg-muted/30 opacity-75 cursor-not-allowed"
                  }`}
                  onClick={() => accessible && setLocation(card.href)}
                >
                  <div className="flex items-start gap-3">
                    <div className={`w-10 h-10 rounded-xl ${card.iconBg} flex items-center justify-center flex-shrink-0`}>
                      {accessible
                        ? <Icon size={20} className={card.iconColor} />
                        : <Lock size={18} className="text-muted-foreground" />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <h3 className="font-bold text-sm leading-tight" data-testid={`text-card-title-${card.id}`}>
                          {card.title}
                        </h3>
                        {card.badge && accessible && (
                          <span className={`px-1.5 py-0.5 rounded text-xs font-black uppercase tracking-wider ${card.iconBg} ${card.iconColor}`}>
                            {card.badge}
                          </span>
                        )}
                        {!accessible && (
                          <span className="px-1.5 py-0.5 rounded text-xs font-bold uppercase tracking-wider bg-muted text-muted-foreground">
                            Restricted
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                        {card.description}
                      </p>
                    </div>
                  </div>
                  {accessible && (
                    <div className="flex justify-end">
                      <span className={`inline-flex items-center gap-1 text-xs font-semibold ${card.iconColor}`}>
                        Open <ChevronRight size={13} />
                      </span>
                    </div>
                  )}
                </motion.div>
              );
            })}
          </div>
        </div>

        {/* Staff Engagement (director+) */}
        {effectiveRank >= LEADERSHIP_RANK["director"] && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border border-border bg-card overflow-hidden"
            data-testid="card-staff-engagement"
          >
            <div className="p-5 border-b border-border flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center flex-shrink-0">
                <Star size={20} className="text-amber-500" fill="currentColor" />
              </div>
              <div className="flex-1 min-w-0">
                <h2 className="font-bold text-sm">Staff Engagement</h2>
                <p className="text-xs text-muted-foreground">Points earned across your facility</p>
              </div>
            </div>

            {!staffEngagement ? (
              <div className="p-5 flex flex-col gap-3">
                {[1,2,3].map(i => <div key={i} className="h-10 rounded-xl bg-muted/40 animate-pulse" />)}
              </div>
            ) : staffEngagement.length === 0 ? (
              <div className="p-8 text-center text-muted-foreground">
                <Brain size={28} className="mx-auto mb-2 opacity-30" />
                <p className="text-sm font-semibold">No activity yet</p>
                <p className="text-xs mt-1">Points appear here once staff start quizzes or flashcard reviews.</p>
              </div>
            ) : (
              <div className="divide-y divide-border/60">
                {staffEngagement.map((member, i) => {
                  const name = (member.firstName || member.lastName)
                    ? `${member.firstName} ${member.lastName}`.trim()
                    : member.username;
                  const initial = name.charAt(0).toUpperCase();
                  return (
                    <div
                      key={member.userId}
                      className="px-5 py-3.5 flex items-center gap-3"
                      data-testid={`row-engagement-${member.userId}`}
                    >
                      <div className="w-6 text-center flex-shrink-0">
                        <span className="text-xs font-black text-muted-foreground">{i + 1}</span>
                      </div>
                      <div className="w-8 h-8 rounded-full bg-amber-500/10 flex items-center justify-center flex-shrink-0">
                        <span className="text-xs font-bold text-amber-600">{initial}</span>
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <p className="text-sm font-bold truncate">{name}</p>
                          <span className={`flex-shrink-0 text-[10px] font-bold px-1.5 py-0.5 rounded-full ${
                            member.engagementLevel === "High"
                              ? "bg-emerald-500/15 text-emerald-600"
                              : member.engagementLevel === "Medium"
                              ? "bg-amber-500/15 text-amber-600"
                              : "bg-muted text-muted-foreground"
                          }`} data-testid={`badge-engagement-level-${member.userId}`}>
                            {member.engagementLevel}
                          </span>
                        </div>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground mt-0.5">
                          {member.department && <span>{member.department}</span>}
                          <span className="flex items-center gap-1">
                            <BookOpen size={10} />
                            {member.questionsCorrect} correct
                          </span>
                          <span className="flex items-center gap-1">
                            <Brain size={10} />
                            {member.flashcardsReviewed} cards
                          </span>
                          {member.finalsCompleted > 0 && (
                            <span className="flex items-center gap-1 text-primary font-semibold">
                              <GraduationCap size={10} />
                              {member.finalsCompleted} exam{member.finalsCompleted !== 1 ? "s" : ""}
                            </span>
                          )}
                        </div>
                      </div>
                      <div className="flex-shrink-0 flex items-center gap-1">
                        <Star size={13} className="text-amber-500" fill="currentColor" />
                        <span className="font-black text-sm" data-testid={`text-engagement-points-${member.userId}`}>
                          {member.totalPoints.toLocaleString()}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </motion.div>
        )}

        {/* Permission summary */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="rounded-xl border border-border bg-card p-4"
          data-testid="card-permission-summary"
        >
          <h3 className="font-bold text-xs uppercase tracking-wider text-muted-foreground mb-3 flex items-center gap-1.5">
            <ShieldCheck size={13} />
            Access Summary
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
            {[
              { label: "Your Role", value: leadershipLabel, testid: "text-summary-role" },
              { label: "Module", value: moduleLabel, testid: "text-summary-module" },
              { label: "Scope", value: effectiveRank >= 3 ? "All Facilities" : "Own Facility", testid: "text-summary-scope" },
              { label: "Data Access", value: isAsc ? "ASC Only" : isDnv ? "DNV Only" : "Hospital Only", testid: "text-summary-data" },
            ].map(item => (
              <div key={item.label} className="flex flex-col gap-0.5">
                <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">{item.label}</span>
                <span className="text-sm font-bold" data-testid={item.testid}>{item.value}</span>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Back to learning */}
        <div className="flex justify-center">
          <Button
            variant="outline"
            onClick={() => setLocation("/dashboard")}
            data-testid="button-back-to-learning"
            className="gap-2"
          >
            <ArrowLeft size={15} />
            Back to Training Dashboard
          </Button>
        </div>
      </div>
    </div>
  );
}
