import type { Question } from "./schema";

export interface DnvPosttestQuestion extends Question {
  chapterId: string;
  chapterName: string;
}

export const dnvPosttestQuestions: DnvPosttestQuestion[] = [
  // ── Quality Management System (3) ──────────────────────────────────────────
  {
    id: "dnv_post_qm_01",
    chapterId: "dnv_qm",
    chapterName: "Quality Management System",
    question: "A hospital's Management Representative reports QMS performance only to department heads and never upward to the governing body or CEO. Under NIAHO QM.4, this arrangement is:",
    options: ["Compliant — department heads can relay information upward", "Non-compliant — the Management Representative must report QMS performance directly to top leadership", "Compliant if the department heads are on the quality committee", "Non-compliant only during active NIAHO survey"],
    correctIndex: 1,
    explanation: "QM.4 requires the Management Representative to report QMS performance to top management (CEO and governing body). Filtering through department heads breaks the direct accountability chain required by NIAHO.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO QM.4",
    tutor: {
      whyCorrect: "The Management Representative's upward reporting function is the mechanism by which leadership maintains visibility into QMS performance. This is a fundamental ISO 9001/NIAHO accountability requirement.",
      whyWrong: { A: "Relay through department heads introduces filtering and delay that breaks the direct reporting chain.", C: "Committee membership does not substitute for the direct upward reporting requirement.", D: "NIAHO compliance requirements are continuous — not just during surveys." },
      operationalContext: "Include a standing agenda item on the governing body and CEO meeting schedules for Management Representative QMS status reports. Document these discussions in meeting minutes.",
    },
  },
  {
    id: "dnv_post_qm_02",
    chapterId: "dnv_qm",
    chapterName: "Quality Management System",
    question: "Under NIAHO QM.3, the Quality Outline/Plan must be:",
    options: ["Approved by CMS before implementation", "Maintained current and reviewed when significant organizational changes occur", "Reviewed only during the NIAHO re-accreditation survey cycle", "Signed annually by every department head"],
    correctIndex: 1,
    explanation: "QM.3 requires the Quality Outline/Plan to be maintained current. It must be reviewed — and updated if necessary — when significant changes occur, such as new services, leadership changes, or major process redesigns.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO QM.3",
    tutor: {
      whyCorrect: "A Quality Outline/Plan that does not reflect the current state of the organization is non-compliant. The review trigger is significant change, not just the annual calendar.",
      whyWrong: { A: "CMS pre-approval is not required for internal quality plans.", C: "Waiting for the survey cycle to review the plan means the document may be outdated for months or years.", D: "Annual department head signatures are not a NIAHO QM.3 requirement." },
      operationalContext: "Track Quality Outline/Plan review dates in your document management system and link review triggers to your change management process.",
    },
  },
  {
    id: "dnv_post_qm_03",
    chapterId: "dnv_qm",
    chapterName: "Quality Management System",
    question: "The ISO 9001 principle most directly aligned with patient-centered care under NIAHO is:",
    options: ["Relationship management", "Evidence-based decision making", "Customer focus", "Leadership engagement"],
    correctIndex: 2,
    explanation: "ISO 9001's 'customer focus' principle translates directly to patient focus in healthcare. Understanding and meeting patient needs and expectations is the foundation of NIAHO's quality philosophy.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO QM.2",
    tutor: {
      whyCorrect: "In healthcare, the 'customer' is the patient. Customer focus means understanding patient requirements, meeting those requirements, and aiming to exceed expectations — the core of patient-centered care.",
      whyWrong: { A: "Relationship management is about partnerships and suppliers — less directly aligned to patient-centered care.", B: "Evidence-based decision making drives quality improvement but is not the primary patient-centered principle.", D: "Leadership engagement enables the quality system but is not the patient-centered principle." },
      operationalContext: "Frame your quality improvement presentations to the governing body in patient-centered language — how do our quality metrics reflect our patients' experience and outcomes?",
    },
  },
  // ── Governance & Leadership (2) ────────────────────────────────────────────
  {
    id: "dnv_post_gov_01",
    chapterId: "dnv_gov",
    chapterName: "Governance & Leadership",
    question: "Under NIAHO, when the hospital contracts with an outside vendor for a clinical service, the hospital's legal accountability for that service:",
    options: ["Transfers to the contracted vendor upon contract execution", "Remains with the hospital — accountability cannot be contracted away", "Is shared equally between the hospital and vendor", "Transfers to the governing body's legal counsel"],
    correctIndex: 1,
    explanation: "NIAHO GB.2 is explicit: the hospital cannot outsource legal accountability to a vendor. The hospital remains responsible for contracted services meeting the same standards as directly provided services.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO GB.2",
    tutor: {
      whyCorrect: "The governing body must oversee contracted services with the same rigor as direct services. Vendor contracts must include quality standards, and performance must be monitored.",
      whyWrong: { A: "Legal accountability under NIAHO is non-transferable regardless of contract terms.", C: "Shared accountability is not a NIAHO concept — the hospital retains full accountability.", D: "Legal counsel does not assume accountability; they advise on the hospital's obligations." },
      operationalContext: "Include NIAHO quality standards in all clinical vendor contracts. Build vendor performance monitoring into your quality committee agenda.",
    },
  },
  {
    id: "dnv_post_gov_02",
    chapterId: "dnv_gov",
    chapterName: "Governance & Leadership",
    question: "Under NIAHO, the governing body's review of credentialing recommendations from the medical staff must involve:",
    options: ["Immediate approval as a formality — the medical staff is the clinical authority", "Independent, substantive review before granting privileges", "CMS verification of credentials before governing body action", "A 30-day public comment period for community input"],
    correctIndex: 1,
    explanation: "The governing body must independently review credentialing recommendations — not rubber-stamp them. This means reviewing actual competency evidence, asking questions, and making an independent decision to grant, limit, or deny privileges.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO GB.2",
    tutor: {
      whyCorrect: "Independent review is the distinction between true governance and a rubber-stamp. Surveyors look at governing body credentialing meeting minutes to assess whether substantive discussion occurred.",
      whyWrong: { A: "The medical staff's clinical expertise informs but does not replace the governing body's credentialing authority.", C: "CMS verification is not part of the hospital credentialing process.", D: "Public comment periods are not part of NIAHO credentialing requirements." },
      operationalContext: "Ensure governing body credentialing committee meeting minutes reflect questions asked, data reviewed, and the basis for privilege decisions — not just vote tallies.",
    },
  },
  // ── Medical Staff (3) ──────────────────────────────────────────────────────
  {
    id: "dnv_post_ms_01",
    chapterId: "dnv_ms",
    chapterName: "Medical Staff",
    question: "A physician successfully completes FPPE for a new privilege. The ongoing monitoring process that follows is called:",
    options: ["Focused Professional Practice Evaluation (FPPE) — extended phase", "Ongoing Professional Practice Evaluation (OPPE)", "Continuous Quality Improvement Review (CQIR)", "Annual Privilege Re-evaluation (APR)"],
    correctIndex: 1,
    explanation: "After FPPE is completed successfully, NIAHO requires Ongoing Professional Practice Evaluation (OPPE) — a continuous monitoring process that collects performance data on all practitioners and informs privilege renewal decisions.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MS",
    tutor: {
      whyCorrect: "OPPE is data-driven and continuous. It typically includes volume data, outcomes data, peer review findings, and compliance metrics. OPPE findings can trigger a new FPPE if concerns emerge.",
      whyWrong: { A: "FPPE is time-limited for a specific trigger; it does not extend indefinitely into ongoing monitoring.", C: "CQIR is not a NIAHO-defined process.", D: "APR is not a NIAHO term; privilege renewal is driven by OPPE data, not a separate annual process." },
      operationalContext: "Build OPPE dashboards for each medical staff member so department chiefs can review performance data at least every 6-12 months before privilege renewal.",
    },
  },
  {
    id: "dnv_post_ms_02",
    chapterId: "dnv_ms",
    chapterName: "Medical Staff",
    question: "Under NIAHO, who has the final authority to grant, limit, or revoke clinical privileges?",
    options: ["The Chief of Staff, acting on peer review findings", "The governing body, acting on medical staff recommendations", "The CEO, after reviewing quality committee reports", "The state medical board, for licensed physicians"],
    correctIndex: 1,
    explanation: "Under NIAHO, the governing body holds the final authority to grant, limit, or revoke clinical privileges. The medical staff evaluates and recommends; the governing body decides.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MS / GB",
    tutor: {
      whyCorrect: "This is a critical governance principle. The governing body cannot delegate final privileging authority to the medical staff, the CEO, or any committee. The board must take the final action.",
      whyWrong: { A: "The Chief of Staff leads the medical staff process but does not hold final authority.", C: "The CEO manages operations but does not hold final privileging authority.", D: "The state medical board licenses practitioners; the hospital governs their scope of practice within the hospital." },
      operationalContext: "Ensure your medical staff bylaws clearly define the governing body as the final authority for privileging decisions. This language is reviewed by NIAHO surveyors.",
    },
  },
  {
    id: "dnv_post_ms_03",
    chapterId: "dnv_ms",
    chapterName: "Medical Staff",
    question: "Under NIAHO MS, what must medical staff bylaws define regarding the organization of the medical staff?",
    options: ["Only the credentialing process timelines", "Organization, responsibilities, and accountability of the medical staff to the governing body", "The salary structure for employed physicians", "The specific clinical protocols for common diagnoses"],
    correctIndex: 1,
    explanation: "NIAHO requires medical staff bylaws to define the organization, responsibilities, and accountability structure of the medical staff — including how the medical staff relates to and reports to the governing body.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MS",
    tutor: {
      whyCorrect: "Bylaws are the constitutional document of the medical staff. They define governance structure, meeting requirements, appointment and reappointment processes, and the relationship between the medical staff and governing body.",
      whyWrong: { A: "Credentialing timelines are in bylaws but are not the only required content.", C: "Physician compensation is an employment matter, not a bylaws requirement.", D: "Clinical protocols are policies and procedures, not bylaw content." },
      operationalContext: "Review medical staff bylaws annually for consistency with current NIAHO requirements. NIAHO surveyors review bylaws for completeness and compliance.",
    },
  },
  // ── Nursing & Staffing Management (2) ─────────────────────────────────────
  {
    id: "dnv_post_ns_01",
    chapterId: "dnv_ns",
    chapterName: "Nursing & Staffing Management",
    question: "Under NIAHO NS, what must be demonstrated to ensure that patient care assignments are appropriate for each nursing staff member?",
    options: ["The nurse has held their current license for at least 2 years", "Documented competency matched to the specific patient care needs assigned", "Completion of annual mandatory education modules", "The nurse-to-patient ratio does not exceed state guidelines"],
    correctIndex: 1,
    explanation: "NIAHO NS requires patient care assignments to be based on documented competency specific to the patient population and care needs. License tenure and mandatory education completion alone do not satisfy the competency-based assignment requirement.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO NS",
    tutor: {
      whyCorrect: "Competency documentation must be specific — a nurse assigned to the ICU must have documented ICU competencies. Annual education modules provide general knowledge but do not validate unit-specific competency.",
      whyWrong: { A: "License tenure is irrelevant to specific competency verification.", C: "Mandatory education modules are a foundation but do not replace skill-specific competency validation.", D: "State ratio guidelines set minimums; NIAHO requires competency alignment, not just numeric ratios." },
      operationalContext: "Maintain a competency matrix for each nursing unit. Before assigning a float nurse, verify they hold the unit-specific competencies required for the patient population.",
    },
  },
  {
    id: "dnv_post_ns_02",
    chapterId: "dnv_ns",
    chapterName: "Nursing & Staffing Management",
    question: "A hospital uses only historical budget data to set staffing levels and does not adjust for patient acuity changes during a shift. Under NIAHO Staffing Management (SM), this practice is:",
    options: ["Compliant if budgeted ratios were approved by the governing body", "Non-compliant — staffing must respond to real-time patient care needs and acuity", "Compliant if no adverse events have occurred due to staffing", "Non-compliant only if the hospital is below state minimum staffing ratios"],
    correctIndex: 1,
    explanation: "NIAHO SM requires staffing to be based on patient care needs and acuity — which can change during a shift. Static budget-based staffing that does not respond to real-time acuity changes does not meet the standard.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO SM",
    tutor: {
      whyCorrect: "NIAHO expects a dynamic staffing process — the hospital must have a mechanism to identify acuity changes and adjust assignments or flex staffing accordingly during each shift.",
      whyWrong: { A: "Governing body approval of a budget does not override the real-time acuity-based staffing requirement.", C: "Absence of adverse events is not evidence of compliance; it is an outcome measure.", D: "State minimums are a floor; NIAHO's acuity-based standard is an additional requirement." },
      operationalContext: "Implement a charge nurse huddle protocol at shift change to assess unit acuity, review assignments, and escalate staffing needs before patient safety is affected.",
    },
  },
  // ── Medication Management (2) ──────────────────────────────────────────────
  {
    id: "dnv_post_mm_01",
    chapterId: "dnv_mm",
    chapterName: "Medication Management",
    question: "A physician writes a blanket standing order for 'IV morphine 2–4mg q4h PRN pain for all post-op patients' without patient-specific review. Under NIAHO MM, this order is:",
    options: ["Compliant — standard post-op analgesic protocols are accepted practice", "Non-compliant — NIAHO requires medication orders to be patient-specific", "Compliant if the pharmacy reviews it before dispensing", "Non-compliant only if the patient has a documented allergy"],
    correctIndex: 1,
    explanation: "NIAHO MM requires medication orders to be patient-specific. Blanket standing orders applied to all patients without individual clinical review do not meet the standard and create patient safety risks.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MM",
    tutor: {
      whyCorrect: "Patient-specific orders account for individual factors: weight, renal function, prior opioid use, allergy history, and clinical status. A blanket order ignores these variables.",
      whyWrong: { A: "Standard protocols are acceptable when individualized to the specific patient; a blanket population order is not.", C: "Pharmacy review is a safety layer but does not correct the lack of patient-specific clinical decision making at the ordering stage.", D: "The problem is the non-individualized order, not just allergy absence." },
      operationalContext: "Replace standing blanket orders with order sets that require patient-specific parameters (weight-based dosing, documented allergy check) before an order is activated.",
    },
  },
  {
    id: "dnv_post_mm_02",
    chapterId: "dnv_mm",
    chapterName: "Medication Management",
    question: "Under NIAHO MM, when a medication error results in patient harm, what is the required response?",
    options: ["Report to the state pharmacy board within 24 hours", "Document the error, analyze through the Patient Safety System, and implement corrective action", "Remove the responsible nurse from medication administration duties pending investigation", "Notify the patient's family and close the chart"],
    correctIndex: 1,
    explanation: "NIAHO MM requires medication errors causing harm to be documented, analyzed through the QM.8 Patient Safety System for root cause, and addressed through corrective action to prevent recurrence.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MM / QM.8",
    tutor: {
      whyCorrect: "The Patient Safety System (QM.8) is the mechanism for capturing adverse events and near misses. Medication errors causing harm are adverse events that must enter this system for analysis and improvement.",
      whyWrong: { A: "State pharmacy board reporting may be required by state law but is separate from the NIAHO internal process.", C: "Punitive responses to individual staff undermine the non-punitive culture required by QM.8.", D: "Family notification and chart closure are important steps but do not constitute the full NIAHO required response." },
      operationalContext: "Build medication error reporting directly into your electronic incident reporting system with automatic routing to the pharmacy director and quality department.",
    },
  },
  // ── Surgical & Anesthesia Services (2) ────────────────────────────────────
  {
    id: "dnv_post_ss_01",
    chapterId: "dnv_ss",
    chapterName: "Surgical & Anesthesia Services",
    question: "Under NIAHO AS, the post-anesthesia assessment must be documented and completed:",
    options: ["Within 1 hour of the procedure ending", "Before the patient is discharged from the post-anesthesia care unit (PACU)", "Before the next scheduled surgery begins in that OR", "Within 24 hours of the procedure by the anesthesiologist"],
    correctIndex: 1,
    explanation: "NIAHO AS requires the post-anesthesia assessment to be documented and completed before the patient is discharged from PACU. It must assess the patient's readiness for discharge from anesthesia monitoring.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO AS",
    tutor: {
      whyCorrect: "The post-anesthesia assessment evaluates return of consciousness, airway patency, hemodynamic stability, pain control, and PONV — all required before the anesthesiologist signs off on PACU discharge.",
      whyWrong: { A: "A fixed 1-hour timeline is not the NIAHO requirement; the trigger is PACU discharge readiness.", C: "The timing is patient-specific and not tied to OR scheduling.", D: "24 hours is far beyond the required timeframe; the assessment must precede PACU discharge." },
      operationalContext: "Use a standardized PACU discharge scoring tool (Aldrete or Modified Aldrete) and require the anesthesiologist to document post-anesthesia assessment completion before PACU discharge is signed.",
    },
  },
  {
    id: "dnv_post_ss_02",
    chapterId: "dnv_ss",
    chapterName: "Surgical & Anesthesia Services",
    question: "Under NIAHO SS, who is responsible for obtaining informed consent for a surgical procedure?",
    options: ["The pre-admission nursing team, who can document consent during registration", "The physician performing the procedure", "Any licensed clinical staff member present at the time of consent", "The anesthesiologist, since anesthesia risk is the primary concern"],
    correctIndex: 1,
    explanation: "NIAHO SS.9 requires informed consent to be obtained by the physician performing the procedure. This ensures the person explaining the procedure, its risks, alternatives, and expected outcomes is the one actually performing it.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO SS.9",
    tutor: {
      whyCorrect: "The operating surgeon has the specific knowledge of the procedure's technical details, individualized risks, and alternatives. Informed consent is a physician-patient conversation, not a documentation task.",
      whyWrong: { A: "Nursing staff can facilitate the consent process but cannot obtain surgical informed consent.", C: "'Any licensed staff' does not satisfy the requirement that the performing physician obtain consent.", D: "The anesthesiologist obtains anesthesia consent separately; they do not obtain surgical consent." },
      operationalContext: "Implement a surgical safety checklist item confirming the operating surgeon obtained consent before the patient is brought to the OR. Document who obtained consent in the surgical record.",
    },
  },
  // ── Patient Care Services (3) ──────────────────────────────────────────────
  {
    id: "dnv_post_pc_01",
    chapterId: "dnv_pc",
    chapterName: "Patient Care Services",
    question: "Under NIAHO Nuclear Medicine Services (NM), who must oversee the nuclear medicine program?",
    options: ["A radiologist with general imaging experience", "A qualified nuclear medicine physician", "The hospital's Chief Medical Officer by default", "A nuclear pharmacist licensed by the state"],
    correctIndex: 1,
    explanation: "NIAHO NM requires nuclear medicine services to be overseen by a physician specifically qualified in nuclear medicine — not a general radiologist or CMO by default. The director must have the credentials specific to nuclear medicine practice.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO NM",
    tutor: {
      whyCorrect: "Nuclear medicine involves radioactive materials and specialized imaging techniques that require specific training and licensure beyond general radiology. The program director must hold these qualifications.",
      whyWrong: { A: "General imaging experience does not qualify a radiologist to direct a nuclear medicine program without nuclear medicine-specific credentials.", C: "The CMO's title does not confer nuclear medicine qualifications.", D: "A nuclear pharmacist manages radiopharmaceuticals but does not direct the clinical nuclear medicine program." },
      operationalContext: "Verify your nuclear medicine director's credentials annually and document their licensure for radioactive material use in your compliance files.",
    },
  },
  {
    id: "dnv_post_pc_02",
    chapterId: "dnv_pc",
    chapterName: "Patient Care Services",
    question: "Under NIAHO Rehabilitation Services (RS), what must precede the provision of specialized rehabilitative care?",
    options: ["Patient's verbal agreement to participate in therapy", "A physician order and individualized plan of care", "Insurance authorization for the therapy services", "A minimum 48-hour post-admission waiting period"],
    correctIndex: 1,
    explanation: "NIAHO RS requires specialized rehabilitative services to be provided under a physician's written order, with an individualized plan of care developed by qualified rehabilitation professionals.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO RS",
    tutor: {
      whyCorrect: "The physician order establishes clinical accountability for the decision to initiate rehab. The individualized plan of care ensures services are tailored to the patient's specific functional goals and needs.",
      whyWrong: { A: "Verbal patient agreement is important for person-centered care but does not replace the physician order requirement.", C: "Insurance authorization is a billing requirement, not a NIAHO clinical prerequisite.", D: "NIAHO does not impose a 48-hour waiting period before rehabilitation services begin." },
      operationalContext: "Build rehabilitation order initiation triggers into your admission assessment workflow — patients meeting rehab criteria should receive a physician order and plan of care on day 1.",
    },
  },
  {
    id: "dnv_post_pc_03",
    chapterId: "dnv_pc",
    chapterName: "Patient Care Services",
    question: "Under NIAHO Medical Imaging (MI), which type of equipment maintenance arrangement is NOT eligible for an AEM program?",
    options: ["Ventilators in the ICU", "Imaging and radiological equipment", "Patient monitoring devices in step-down units", "Infusion pumps used on medical-surgical floors"],
    correctIndex: 1,
    explanation: "NIAHO PE.7 (adopted in MI context) explicitly excludes imaging/radiological equipment from AEM programs — these must be maintained per manufacturer recommendations, as required by 42 CFR 482.26(b)(2).",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MI / PE.7",
    tutor: {
      whyCorrect: "Federal regulation mandates manufacturer-specified maintenance for imaging equipment. The AEM option does not apply to this equipment category, regardless of risk assessment findings.",
      whyWrong: { A: "ICU ventilators are eligible for AEM programs if a documented risk assessment supports it.", C: "Step-down monitoring devices can be placed in AEM programs with appropriate risk documentation.", D: "Infusion pumps are eligible for AEM programs with documented risk assessment." },
      operationalContext: "Flag imaging equipment in your maintenance management system as 'manufacturer maintenance only — AEM ineligible.' This prevents accidental inclusion in AEM programs.",
    },
  },
  // ── Emergency & Outpatient Services (2) ───────────────────────────────────
  {
    id: "dnv_post_es_01",
    chapterId: "dnv_es",
    chapterName: "Emergency & Outpatient Services",
    question: "Under NIAHO PE.6, emergency preparedness exercises must be conducted at minimum how many times per year, and what type is specifically required?",
    options: ["Once per year; any type chosen by the hospital", "Twice per year; at least one must be a community-based exercise", "Four times per year; two must be tabletop exercises", "Once per year; must be a full-scale functional exercise"],
    correctIndex: 1,
    explanation: "NIAHO PE.6 requires at least two emergency preparedness exercises annually. At least one must be community-based — involving coordination with external agencies, community partners, or the local emergency management system.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO PE.6",
    tutor: {
      whyCorrect: "Community-based exercises test the hospital's ability to integrate with the broader emergency response system — not just internal operations. Real disasters require external coordination.",
      whyWrong: { A: "One exercise per year does not meet the minimum; two are required.", C: "Four exercises is more than required; tabletop frequency is not specified at four.", D: "Full-scale functional exercises are the highest level but NIAHO does not require all exercises to be full-scale." },
      operationalContext: "Coordinate with your county emergency management agency to schedule a community-based exercise annually. Document after-action reviews and any plan improvements that result.",
    },
  },
  {
    id: "dnv_post_es_02",
    chapterId: "dnv_es",
    chapterName: "Emergency & Outpatient Services",
    question: "Under NIAHO Dietary Services (DS), who must develop therapeutic diets that deviate from standard hospital menus?",
    options: ["The attending physician who ordered the special diet", "A qualified dietitian, with physician order for the therapeutic diet", "The unit charge nurse based on nursing assessment", "A nutritional consultant hired on a per-visit basis"],
    correctIndex: 1,
    explanation: "NIAHO DS requires that therapeutic diets be developed under dietitian supervision and ordered by the physician. The dietitian develops the diet plan; the physician provides the order. Both roles are required.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO DS",
    tutor: {
      whyCorrect: "Therapeutic diets (renal, cardiac, diabetic, enteral) require the specialized knowledge of a qualified dietitian for proper formulation. The physician order establishes the clinical indication.",
      whyWrong: { A: "The physician provides the order but does not develop the therapeutic diet plan.", C: "Nursing assessment informs the dietitian but nurses do not develop therapeutic diets.", D: "A per-visit consultant may serve as the dietitian but must be qualified and meet NIAHO's requirements for the dietary program." },
      operationalContext: "Establish a standard workflow: physician order → dietitian assessment and diet plan development → diet implementation. Document all three steps in the medical record.",
    },
  },
  // ── Patient Rights (2) ────────────────────────────────────────────────────
  {
    id: "dnv_post_pr_01",
    chapterId: "dnv_pr",
    chapterName: "Patient Rights",
    question: "Under NIAHO PR.6, patients must be informed of the hospital's grievance process:",
    options: ["Only when they formally request information", "At the time of admission", "After their first complaint is submitted", "During annual patient satisfaction surveys"],
    correctIndex: 1,
    explanation: "PR.6 requires patients to be informed of the grievance process at admission. This ensures patients know their rights to complain formally and understand how to use the process from the beginning of their care.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO PR.6",
    tutor: {
      whyCorrect: "Informing patients at admission sets expectations and empowers them to advocate for their care. The admission packet must include grievance process information in a language the patient understands.",
      whyWrong: { A: "Waiting for patient requests means most patients never learn about the process.", C: "Informing patients after they've already complained is too late; they must be informed proactively.", D: "Annual surveys are retrospective data collection, not a patient rights education mechanism." },
      operationalContext: "Include grievance process information in your patient admission packet and have nursing staff verbally review it during admission assessment. Document that education was provided.",
    },
  },
  {
    id: "dnv_post_pr_02",
    chapterId: "dnv_pr",
    chapterName: "Patient Rights",
    question: "Under NIAHO PR.3, advance directives must be:",
    options: ["Verified with the patient's attorney before implementation", "Honored and documented in the medical record", "Re-signed at each hospital admission", "Reviewed by the ethics committee before clinical staff act on them"],
    correctIndex: 1,
    explanation: "PR.3 requires advance directives to be honored and documented in the medical record. Clinical staff must be aware of and act in accordance with the patient's documented wishes.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO PR.3",
    tutor: {
      whyCorrect: "The advance directive is the patient's expression of their healthcare wishes when they are unable to communicate. Documentation in the chart ensures all treating clinicians can access and honor those wishes.",
      whyWrong: { A: "Attorney verification is not a clinical requirement for advance directive implementation.", C: "Valid advance directives do not need to be re-executed at each admission; existing documents must be honored.", D: "Ethics committee review is not required before honoring advance directives; it is available when there is conflict." },
      operationalContext: "Build an advance directive flag into your EHR that alerts all treating clinicians when one is on file. Conduct training on recognizing and honoring advance directives in emergency situations.",
    },
  },
  // ── Infection Control & Medical Records (2) ───────────────────────────────
  {
    id: "dnv_post_ic_01",
    chapterId: "dnv_ic",
    chapterName: "Infection Control & Medical Records",
    question: "Under NIAHO IC, the infection control program must address infection prevention and control across:",
    options: ["Only direct patient care departments (ICU, Med/Surg, OR)", "All hospital departments and contracted services", "Only departments with a history of infection outbreaks", "Departments with more than 20 patient beds"],
    correctIndex: 1,
    explanation: "NIAHO IC requires the infection control program to cover all hospital departments — including support services, dietary, environmental services, and contracted services — not just direct patient care areas.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO IC",
    tutor: {
      whyCorrect: "Infections can originate in any department. Dietary, laundry, environmental services, and supply chain all have infection prevention responsibilities that must be addressed in the program.",
      whyWrong: { A: "Clinical departments are the most visible risk areas but not the only ones that must be covered.", C: "Past outbreak history does not limit the program scope — all departments are included proactively.", D: "Bed count does not determine which departments are in the infection control program scope." },
      operationalContext: "Review your infection control policies to ensure contracted services (housekeeping, food service, biomed contractors) are explicitly included with specific competency and compliance requirements.",
    },
  },
  {
    id: "dnv_post_ic_02",
    chapterId: "dnv_ic",
    chapterName: "Infection Control & Medical Records",
    question: "Under NIAHO Discharge Planning (DC), what must be documented in the discharge plan to meet the standard?",
    options: ["Only the patient's next appointment date", "Post-discharge care needs, identified barriers, and follow-up appointments or referrals", "Insurance coverage for post-discharge services", "The physician's attestation that the patient is medically stable for discharge"],
    correctIndex: 1,
    explanation: "NIAHO DC requires a comprehensive discharge plan that addresses post-discharge care needs, identifies barriers to meeting those needs (social, financial, functional), and includes follow-up plan details.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO DC",
    tutor: {
      whyCorrect: "A complete discharge plan prevents avoidable readmissions by ensuring care transitions are planned proactively — not arranged at the last minute. Barriers must be identified and addressed before discharge.",
      whyWrong: { A: "A single appointment date is insufficient; the full care transition plan is required.", C: "Insurance coverage is a consideration but not the primary documentation requirement.", D: "Medical stability attestation is part of the discharge process but is not the discharge plan." },
      operationalContext: "Start discharge planning at admission for all high-risk patients. Use a structured discharge planning tool that prompts assessment of functional status, social support, and follow-up needs.",
    },
  },
  // ── Physical Environment (2) ───────────────────────────────────────────────
  {
    id: "dnv_post_pe_01",
    chapterId: "dnv_pe",
    chapterName: "Physical Environment",
    question: "Under NIAHO PE.1, the Life Safety Code edition that hospitals must comply with is:",
    options: ["The most recent NFPA 101 edition published by the National Fire Protection Association", "The edition adopted by CMS for hospital conditions of participation", "The edition chosen by the hospital's fire marshal", "The edition in effect when the hospital building was constructed"],
    correctIndex: 1,
    explanation: "NIAHO PE.1 requires compliance with the Life Safety Code edition adopted by CMS for hospital Conditions of Participation. CMS specifies which edition applies — hospitals do not choose, and they cannot simply follow the newest published edition without CMS adoption.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO PE.1",
    tutor: {
      whyCorrect: "CMS adopts specific NFPA 101 editions through rulemaking. The CMS-adopted edition is what determines compliance — newer NFPA editions may be published but do not apply until CMS formally adopts them.",
      whyWrong: { A: "The newest published edition is not automatically the compliance standard; CMS adoption determines applicability.", C: "Fire marshals enforce state fire code; the NIAHO standard tracks the CMS-adopted LSC edition.", D: "Original construction code does not determine current compliance requirements." },
      operationalContext: "Subscribe to CMS regulatory updates to track any changes to the adopted Life Safety Code edition. Ensure your life safety compliance program tracks the CMS-adopted version.",
    },
  },
  {
    id: "dnv_post_pe_02",
    chapterId: "dnv_pe",
    chapterName: "Physical Environment",
    question: "Under NIAHO Transfer Agreements and Organ Procurement (TO), what agreement must hospitals have to support organ and tissue procurement?",
    options: ["An agreement with any hospital willing to accept organ donor patients", "A written agreement with a designated Organ Procurement Organization (OPO)", "A state-issued organ procurement license renewed annually", "An informal arrangement documented in medical staff bylaws"],
    correctIndex: 1,
    explanation: "NIAHO TO requires a written agreement with a CMS-certified Organ Procurement Organization (OPO). The hospital must also have a defined process for identifying potential donors and notifying the OPO of all deaths and imminent deaths.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO TO",
    tutor: {
      whyCorrect: "The OPO agreement defines each party's responsibilities: the hospital identifies and refers potential donors; the OPO evaluates suitability and manages the procurement process. The hospital cannot independently determine donor suitability.",
      whyWrong: { A: "An informal arrangement with 'any willing hospital' does not meet the requirement for a written OPO agreement.", C: "No such state organ procurement license for hospitals exists under NIAHO.", D: "Medical staff bylaw provisions do not substitute for the required written OPO agreement." },
      operationalContext: "Review your OPO agreement annually. Ensure your nursing staff is trained to identify and immediately refer all deaths and imminent deaths to the OPO — not just patients who have stated donor intent.",
    },
  },
];
