import type { Question } from "./schema";

export interface DnvTestQuestion extends Question {
  chapterId: string;
  chapterName: string;
}

export const dnvPretestQuestions: DnvTestQuestion[] = [
  // ── Quality Management System (3) ──────────────────────────────────────────
  {
    id: "dnv_pre_qm_01",
    chapterId: "dnv_qm",
    chapterName: "Quality Management System",
    question: "Under NIAHO QM.1, who holds OVERALL ACCOUNTABILITY for the Quality Management System?",
    options: ["The Management Representative", "The CEO", "The Governing Body", "The Chief Quality Officer"],
    correctIndex: 2,
    explanation: "QM.1 places overall accountability for the QMS with the governing body. The CEO is responsible for implementation, and the Management Representative coordinates — but ultimate accountability rests with the governing body.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO QM.1",
    tutor: {
      whyCorrect: "The governing body cannot delegate this ultimate responsibility. Surveyors specifically probe whether the board engages substantively with QMS performance data.",
      whyWrong: { A: "The Management Representative coordinates QMS activities but does not hold overall accountability.", B: "The CEO implements the QMS throughout the organization but reports upward to the governing body.", D: "No such role is defined as the ultimate QMS accountability holder in NIAHO." },
      operationalContext: "Ensure governing body meeting agendas include a standing QMS performance review item with documented discussion and action outputs.",
    },
  },
  {
    id: "dnv_pre_qm_02",
    chapterId: "dnv_qm",
    chapterName: "Quality Management System",
    question: "NIAHO QM.2 requires the hospital's Quality Management System to be explicitly based on which framework?",
    options: ["The Joint Commission ORYX framework", "ISO 9001", "NIST Cybersecurity Framework", "CMS Conditions of Participation only"],
    correctIndex: 1,
    explanation: "NIAHO QM.2 explicitly requires an ISO 9001-based QMS. This is what distinguishes DNV NIAHO from TJC and AAAHC, which do not require ISO 9001 compliance.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO QM.2",
    tutor: {
      whyCorrect: "ISO 9001 brings seven quality management principles to healthcare including customer (patient) focus, process approach, and evidence-based decision making.",
      whyWrong: { A: "ORYX is a TJC performance measurement program, not a NIAHO requirement.", C: "NIST is cited in NIAHO PE.7 for cybersecurity of medical equipment, not the QMS.", D: "CMS CoPs are the baseline; NIAHO adds ISO 9001 on top." },
      operationalContext: "Document your QMS scope, objectives, and management review schedule. These are the three most commonly cited ISO 9001 gaps found during NIAHO surveys.",
    },
  },
  {
    id: "dnv_pre_qm_03",
    chapterId: "dnv_qm",
    chapterName: "Quality Management System",
    question: "Under NIAHO QM.5, before a corrective action may be formally closed, what must be documented?",
    options: ["CEO signature on the action plan", "Verification that the corrective action was effective", "Governing body approval of the closure", "A 90-day monitoring period with no recurrence"],
    correctIndex: 1,
    explanation: "QM.5 requires corrective actions to include root cause analysis, implementation, and effectiveness verification before closure. Closing without verifying effectiveness is one of the most common NIAHO survey findings.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO QM.5",
    tutor: {
      whyCorrect: "Effectiveness verification answers: 'Did the action actually fix the root cause?' The method and result must be documented — not just the action taken.",
      whyWrong: { A: "CEO signature is not a NIAHO closure requirement.", C: "Governing body approval is not required for individual corrective actions.", D: "NIAHO does not prescribe a fixed monitoring period; the hospital defines it based on risk." },
      operationalContext: "Build effectiveness verification into your corrective action tracking tool as a required field — it cannot be marked closed until the verification field is populated.",
    },
  },
  // ── Governance & Leadership (3) ────────────────────────────────────────────
  {
    id: "dnv_pre_gov_01",
    chapterId: "dnv_gov",
    chapterName: "Governance & Leadership",
    question: "Under NIAHO GB.2, who holds LEGAL RESPONSIBILITY for hospital operations?",
    options: ["The state health department", "The governing body", "The CEO", "The medical staff president"],
    correctIndex: 1,
    explanation: "GB.2 places legal responsibility for hospital operations with the governing body — not CMS, the state, or the medical staff. The board must actively oversee quality, approve policies and bylaws, and hold leadership accountable.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO GB.2",
    tutor: {
      whyCorrect: "Legal responsibility includes oversight of quality, credentialing decisions, bylaws, institutional planning, and contracted services. Active oversight means substantive engagement, not rubber-stamping.",
      whyWrong: { A: "The state health department licenses the facility but does not hold legal responsibility for operations.", C: "The CEO implements governing body policies but does not hold legal responsibility.", D: "The medical staff president leads the medical staff but is not the legal responsible party." },
      operationalContext: "Governing body orientation and annual education programs should explicitly cover board member legal duties under NIAHO GB.2.",
    },
  },
  {
    id: "dnv_pre_gov_02",
    chapterId: "dnv_gov",
    chapterName: "Governance & Leadership",
    question: "The CEO's role in the NIAHO Quality Management System is specifically to:",
    options: ["Hold overall accountability", "Implement the QMS throughout the organization", "Coordinate QMS activities as Management Representative", "Approve all corrective actions before closure"],
    correctIndex: 1,
    explanation: "Under QM.1 and CE standards, the CEO is responsible for IMPLEMENTING the QMS throughout the organization. The governing body holds overall accountability; the Management Representative coordinates.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO QM.1 / CE",
    tutor: {
      whyCorrect: "Implementation means active driving — ensuring resources, training, and processes are in place across all departments. A passive CEO creates accountability gaps surveyors probe.",
      whyWrong: { A: "Overall accountability belongs to the governing body.", C: "The Management Representative role (QM.4) is separate from the CEO role.", D: "Corrective action closure is managed through the QMS corrective action process, not CEO approval." },
      operationalContext: "The CEO should present QMS implementation updates to the governing body at each board meeting, not just quality committee meetings.",
    },
  },
  {
    id: "dnv_pre_gov_03",
    chapterId: "dnv_gov",
    chapterName: "Governance & Leadership",
    question: "A governing body that consistently approves all executive recommendations without independent review is:",
    options: ["Compliant — board deference to management is appropriate", "Non-compliant — GB.2 requires active, independent oversight", "Compliant if a quality committee reviews recommendations first", "Non-compliant only if patient harm results"],
    correctIndex: 1,
    explanation: "GB.2 requires genuine active oversight. A board that rubber-stamps management without independent review, substantive questions, or data analysis is not exercising the required oversight and is non-compliant.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO GB.2",
    tutor: {
      whyCorrect: "Active oversight is demonstrated through documented questioning, independent data review, and accountability actions — not just attendance at meetings.",
      whyWrong: { A: "Deference without scrutiny is non-compliance, regardless of outcomes.", C: "A quality committee review does not substitute for governing body independent judgment.", D: "NIAHO does not require harm to occur before GB.2 non-compliance is cited." },
      operationalContext: "Ensure board meeting minutes document substantive discussion, not just vote outcomes. Surveyors review minutes.",
    },
  },
  // ── Medical Staff (2) ──────────────────────────────────────────────────────
  {
    id: "dnv_pre_ms_01",
    chapterId: "dnv_ms",
    chapterName: "Medical Staff",
    question: "Under NIAHO MS, when a physician is initially appointed to the medical staff, what process must be used to evaluate competence?",
    options: ["Peer reference letters alone", "Focused Professional Practice Evaluation (FPPE)", "A 30-day provisional period with no formal structure", "Ongoing Professional Practice Evaluation (OPPE)"],
    correctIndex: 1,
    explanation: "FPPE is required for all newly appointed practitioners and for practitioners granted new privileges. It is a structured, defined period of focused monitoring before privileges are confirmed.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MS",
    tutor: {
      whyCorrect: "FPPE defines the monitoring method, duration, and criteria in advance. It must be documented and completed before privileges are confirmed as ongoing.",
      whyWrong: { A: "Peer references are part of credentialing but do not satisfy FPPE requirements.", C: "A provisional period without a structured monitoring plan does not constitute FPPE.", D: "OPPE is the ongoing monitoring process used after FPPE is successfully completed." },
      operationalContext: "Create an FPPE policy with specific trigger criteria, monitoring activities, and defined evaluation periods for each privilege category.",
    },
  },
  {
    id: "dnv_pre_ms_02",
    chapterId: "dnv_ms",
    chapterName: "Medical Staff",
    question: "Under NIAHO, clinical privileges must be granted based on:",
    options: ["The physician's board certification alone", "Documented competency, training, and experience specific to the privilege requested", "The recommendation of the department chief without further documentation", "Years of service at the hospital"],
    correctIndex: 1,
    explanation: "NIAHO requires clinical privileges to be granted based on documented competency evidence specific to each privilege — including training, experience, and demonstrated performance. Board certification alone is insufficient.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MS",
    tutor: {
      whyCorrect: "The privilege-specific documentation requirement means each privilege category must have its own supporting evidence, not just a blanket credential review.",
      whyWrong: { A: "Board certification is valuable evidence but cannot stand alone; privilege-specific competency documentation is required.", C: "Department chief recommendation must be supported by documented competency evidence.", D: "Tenure is not a NIAHO-accepted basis for granting clinical privileges." },
      operationalContext: "Build privilege-specific competency checklists into your medical staff application forms so each privilege has documented supporting evidence.",
    },
  },
  // ── Nursing & Staffing Management (2) ─────────────────────────────────────
  {
    id: "dnv_pre_ns_01",
    chapterId: "dnv_ns",
    chapterName: "Nursing & Staffing Management",
    question: "Under NIAHO NS, what licensed nursing coverage is required 24 hours a day, 7 days a week?",
    options: ["A licensed practical nurse (LPN)", "A registered nurse (RN)", "A nurse practitioner (NP)", "A clinical nurse specialist (CNS)"],
    correctIndex: 1,
    explanation: "NIAHO NS requires a registered nurse to be on duty 24 hours a day. LPNs and other nursing staff may supplement but cannot substitute for the required RN presence.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO NS",
    tutor: {
      whyCorrect: "The 24/7 RN requirement ensures that a licensed nurse with full scope of practice is available to assess patients, respond to emergencies, and supervise care at all times.",
      whyWrong: { A: "LPNs have a more limited scope of practice; they cannot fulfill the 24/7 RN requirement.", C: "NPs may be present but the standard requires RN, not advanced practice.", D: "CNS may also be present but the foundational requirement is for an RN." },
      operationalContext: "Review night and weekend staffing matrices to confirm RN coverage on all units at all times, including low-census periods when float pools are used.",
    },
  },
  {
    id: "dnv_pre_ns_02",
    chapterId: "dnv_ns",
    chapterName: "Nursing & Staffing Management",
    question: "Under NIAHO Staffing Management (SM), what must the hospital's staffing plans be based on?",
    options: ["Historical budget data alone", "Patient care needs, acuity, and competency of available staff", "A fixed nurse-to-patient ratio set by the state", "The lowest staffing level acceptable to the governing body"],
    correctIndex: 1,
    explanation: "NIAHO SM requires staffing plans to be based on patient care needs and acuity, with staff competency matched to those needs. Budget-only or fixed-ratio approaches do not meet the standard.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO SM",
    tutor: {
      whyCorrect: "Patient acuity drives staffing requirements. The hospital must demonstrate how it assesses acuity and translates that into staffing assignments.",
      whyWrong: { A: "Budget is a constraint but not the basis for safe staffing decisions under NIAHO.", C: "NIAHO does not impose fixed ratios; it requires acuity-based planning.", D: "Governance sets policy but cannot override safe staffing requirements." },
      operationalContext: "Implement a patient acuity scoring tool that links acuity levels to staffing targets. Document the connection between acuity data and staffing decisions.",
    },
  },
  // ── Medication Management (2) ──────────────────────────────────────────────
  {
    id: "dnv_pre_mm_01",
    chapterId: "dnv_mm",
    chapterName: "Medication Management",
    question: "Under NIAHO MM, who is authorized to prescribe and sign medication orders?",
    options: ["Any registered nurse with 5+ years experience", "Licensed independent practitioners with prescriptive authority", "The pharmacy director", "Department managers who have completed medication safety training"],
    correctIndex: 1,
    explanation: "NIAHO MM limits medication orders to licensed independent practitioners with prescriptive authority as defined by state law and medical staff bylaws. This is a core medication safety requirement.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MM",
    tutor: {
      whyCorrect: "The prescriber must hold a license that grants prescriptive authority in the state. Verbal orders must be authenticated by the prescriber within the timeframe defined by hospital policy.",
      whyWrong: { A: "RN experience does not grant prescriptive authority.", C: "Pharmacy directors oversee medication management but do not prescribe (unless separately licensed to do so).", D: "Medication safety training does not confer prescriptive authority." },
      operationalContext: "Ensure your medical staff bylaws define prescriptive authority categories and that prescriber identifiers in your EHR are linked to verified license records.",
    },
  },
  {
    id: "dnv_pre_mm_02",
    chapterId: "dnv_mm",
    chapterName: "Medication Management",
    question: "Under NIAHO MM, what safeguard must be in place for high-alert medications prior to administration?",
    options: ["Mandatory waiting period of 15 minutes", "Independent double-check verification by a second licensed professional", "Pharmacist presence at bedside during administration", "Patient signature on a high-alert medication consent form"],
    correctIndex: 1,
    explanation: "NIAHO MM requires independent double-check verification for high-alert medications. The second check must be truly independent — the second reviewer must not see the first reviewer's answer before making their own assessment.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MM",
    tutor: {
      whyCorrect: "High-alert medications (insulin, heparin, chemotherapy, concentrated electrolytes) have a narrow safety margin; independent double-checks catch dose and patient errors before harm occurs.",
      whyWrong: { A: "A waiting period is not a NIAHO requirement for high-alert medications.", C: "Pharmacist bedside presence is not required unless the hospital policy specifically mandates it.", D: "Patient consent forms are unrelated to the high-alert double-check requirement." },
      operationalContext: "Define your hospital's high-alert medication list in policy, build the independent double-check into your EHR workflow, and audit compliance monthly.",
    },
  },
  // ── Surgical & Anesthesia Services (2) ────────────────────────────────────
  {
    id: "dnv_pre_ss_01",
    chapterId: "dnv_ss",
    chapterName: "Surgical & Anesthesia Services",
    question: "Under NIAHO SS.8, if the operative report cannot be dictated immediately after surgery, what must be placed in the medical record BEFORE the patient is transferred from the OR?",
    options: ["A verbal report to the receiving nurse", "A brief operative note documenting the key findings and procedure", "The pre-operative H&P with post-op vital signs added", "A signed attestation that the report will be completed within 24 hours"],
    correctIndex: 1,
    explanation: "SS.8 requires immediate post-op dictation. If dictation is delayed, a brief operative note must be placed in the record before patient transfer to ensure post-op care continuity. The complete report must follow promptly.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO SS.8",
    tutor: {
      whyCorrect: "The brief op note must include the procedure performed, pre/post diagnosis, and any immediate complications so that recovery room staff have accurate clinical information.",
      whyWrong: { A: "Verbal reports are not a substitute for documentation.", C: "The pre-op H&P is not a replacement for the operative note.", D: "An attestation of future completion does not provide clinical continuity." },
      operationalContext: "Create a brief op note template in your EHR that surgeons can complete in under 2 minutes immediately post-procedure before leaving the OR.",
    },
  },
  {
    id: "dnv_pre_ss_02",
    chapterId: "dnv_ss",
    chapterName: "Surgical & Anesthesia Services",
    question: "Under NIAHO Anesthesia Services (AS), when must the pre-anesthesia evaluation be completed?",
    options: ["Within 24 hours before any procedure", "Before the anesthesia is administered for any procedure", "Immediately after the patient is brought to the OR", "Before the patient's insurance authorization is confirmed"],
    correctIndex: 1,
    explanation: "NIAHO AS requires the pre-anesthesia evaluation to be completed before anesthesia is administered. Its purpose is to identify risk factors, select the anesthesia plan, and obtain informed consent.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO AS",
    tutor: {
      whyCorrect: "The pre-anesthesia evaluation documents the patient's history, airway assessment, ASA classification, and anesthesia plan — all required before any anesthetic is given.",
      whyWrong: { A: "There is no NIAHO-mandated 24-hour window; the requirement is before administration.", C: "Completing evaluation after OR arrival but after anesthesia onset does not satisfy the standard.", D: "Insurance authorization is a billing function, not a NIAHO anesthesia requirement." },
      operationalContext: "Build a pre-anesthesia evaluation completion check into your surgical safety checklist — the case cannot proceed without a completed and signed evaluation.",
    },
  },
  // ── Patient Care Services (3) ──────────────────────────────────────────────
  {
    id: "dnv_pre_pc_01",
    chapterId: "dnv_pc",
    chapterName: "Patient Care Services",
    question: "Under NIAHO Laboratory Services (LS), who must direct the laboratory operations?",
    options: ["A registered nurse with laboratory training", "A qualified laboratory director (pathologist or equivalent)", "The hospital's Chief Medical Officer", "A laboratory technician with 10+ years of experience"],
    correctIndex: 1,
    explanation: "NIAHO LS requires laboratory operations to be directed by a qualified laboratory director — typically a pathologist or a doctoral-level scientist with appropriate credentials. The director is accountable for all laboratory services.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO LS",
    tutor: {
      whyCorrect: "The laboratory director must meet the qualifications defined in CLIA (Clinical Laboratory Improvement Amendments) as adopted by NIAHO. This includes specific education and experience requirements.",
      whyWrong: { A: "RNs do not qualify as laboratory directors under NIAHO/CLIA standards.", C: "The CMO is not qualified by that title alone to direct laboratory services.", D: "Experience alone without the required credentials does not qualify a technician as laboratory director." },
      operationalContext: "Verify your laboratory director's credentials are current and on file. NIAHO surveyors routinely request this documentation.",
    },
  },
  {
    id: "dnv_pre_pc_02",
    chapterId: "dnv_pc",
    chapterName: "Patient Care Services",
    question: "Under NIAHO Respiratory Care Services (RC), who must write the order for respiratory therapy services?",
    options: ["The respiratory therapist providing the service", "A licensed independent practitioner with prescriptive authority", "The Director of Respiratory Care", "A charge nurse after clinical assessment"],
    correctIndex: 1,
    explanation: "NIAHO RC requires respiratory care services to be provided under the written order of a licensed independent practitioner. Respiratory therapists execute, not prescribe, the treatment plan.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO RC",
    tutor: {
      whyCorrect: "This order requirement applies to all respiratory therapy services — ventilator management, aerosol therapy, ABG collection, etc. The ordering practitioner is accountable for the clinical decision.",
      whyWrong: { A: "RT scope of practice is treatment execution, not independent ordering.", C: "The Director of Respiratory Care manages the department but does not independently order services for patients.", D: "Charge nurses do not have independent prescriptive authority." },
      operationalContext: "Audit respiratory care orders quarterly for completeness — missing or incomplete orders are a common NIAHO citation.",
    },
  },
  {
    id: "dnv_pre_pc_03",
    chapterId: "dnv_pc",
    chapterName: "Patient Care Services",
    question: "Under NIAHO Obstetric Services (OB), which practitioner credential is required to attend deliveries?",
    options: ["Any RN who has completed obstetric training", "A physician or certified nurse-midwife with appropriate obstetric privileges", "A certified nursing assistant supervised by an RN", "A medical student in the third year of clinical rotations"],
    correctIndex: 1,
    explanation: "NIAHO OB requires deliveries to be attended by a physician or certified nurse-midwife who holds specific obstetric privileges granted by the medical staff. Privilege scope must match the complexity of the delivery.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO OB",
    tutor: {
      whyCorrect: "The privilege requirement ensures that the clinician attending the delivery has documented competency in obstetric care. Privileges are granted through the medical staff process after competency verification.",
      whyWrong: { A: "RN training does not confer privileges to independently attend deliveries.", C: "CNAs do not have the scope of practice required.", D: "Medical students practice under direct supervision and do not hold independent privileges." },
      operationalContext: "Review obstetric privilege delineation forms to ensure they specify delivery types (vaginal, operative, high-risk) with corresponding competency documentation.",
    },
  },
  // ── Emergency & Outpatient Services (2) ───────────────────────────────────
  {
    id: "dnv_pre_es_01",
    chapterId: "dnv_es",
    chapterName: "Emergency & Outpatient Services",
    question: "Under NIAHO Emergency Services (ES), what must the emergency department maintain at all times to ensure appropriate medical oversight?",
    options: ["A full trauma team on standby", "Physician or qualified practitioner on-call coverage 24/7", "A board-certified emergency physician on site at all times", "Direct telephone access to the nearest Level I trauma center"],
    correctIndex: 1,
    explanation: "NIAHO ES requires 24/7 on-call physician coverage for the emergency department. The on-call physician must be able to respond within the timeframes defined by hospital policy and medical staff bylaws.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO ES",
    tutor: {
      whyCorrect: "The 24/7 coverage requirement ensures that a physician is always reachable and able to respond to emergency patients. Response time expectations must be defined and monitored.",
      whyWrong: { A: "Trauma team standby applies to designated trauma centers; it is not a universal NIAHO requirement.", C: "Board certification is not mandated — qualifications and privileges are; the physician need not be on-site but must be on-call.", D: "Trauma center access is part of transfer agreements, not the 24/7 ED coverage standard." },
      operationalContext: "Document on-call schedules and response time logs. Surveyors may review response times to determine if coverage is effectively available.",
    },
  },
  {
    id: "dnv_pre_es_02",
    chapterId: "dnv_es",
    chapterName: "Emergency & Outpatient Services",
    question: "Under NIAHO Outpatient Services (OS), before outpatient services may be provided, what must be established?",
    options: ["A separate outpatient accreditation from a recognized body", "Written policies and procedures governing the outpatient services offered", "A dedicated outpatient billing system separate from inpatient", "CMS pre-approval for each outpatient service category"],
    correctIndex: 1,
    explanation: "NIAHO OS requires written policies and procedures to govern outpatient services. These must address patient assessment, care delivery, medication management, and discharge criteria applicable to the outpatient setting.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO OS",
    tutor: {
      whyCorrect: "Written policies ensure consistent care delivery and provide the framework surveyors use to assess whether outpatient services meet the standard of care required by NIAHO.",
      whyWrong: { A: "Separate outpatient accreditation is not required by NIAHO for hospital outpatient services.", C: "Billing system structure is an operational choice, not a NIAHO requirement.", D: "CMS pre-approval is not required for each outpatient service type under NIAHO." },
      operationalContext: "Review your outpatient policies annually and after any service additions. Ensure policies are accessible to all outpatient staff.",
    },
  },
  // ── Patient Rights (2) ────────────────────────────────────────────────────
  {
    id: "dnv_pre_pr_01",
    chapterId: "dnv_pr",
    chapterName: "Patient Rights",
    question: "Under NIAHO PR.7, what must occur before a restraint may be applied to a patient?",
    options: ["Family notification within 1 hour", "A physician order for the specific restraint type", "A 30-minute trial of a less restrictive intervention documented in the chart", "Governing body approval of a restraint protocol"],
    correctIndex: 1,
    explanation: "PR.7 requires a physician order before any restraint is applied. Orders must be time-limited, not standing orders. Each episode requires a new order with clinical justification.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO PR.7",
    tutor: {
      whyCorrect: "The physician order requirement ensures clinical accountability for the decision to use restraint. Time-limited orders force re-evaluation and prevent indefinite restraint use.",
      whyWrong: { A: "Family notification is a courtesy and documentation requirement but does not precede the restraint order.", C: "Least restrictive alternatives must be considered, but the documentation of a 30-minute trial is not a NIAHO requirement prior to ordering.", D: "Governing body restraint protocol approval is required at a policy level, not per patient episode." },
      operationalContext: "Implement a restraint order set in your EHR that auto-expires based on patient age category (1 hr child / 2 hr adolescent / 4 hr adult) and requires re-evaluation documentation.",
    },
  },
  {
    id: "dnv_pre_pr_02",
    chapterId: "dnv_pr",
    chapterName: "Patient Rights",
    question: "Under NIAHO PR.9, a death associated with restraint or seclusion use must be reported to CMS within:",
    options: ["72 hours of the death", "1 business day of the death", "30 days in the next annual report", "7 days if restraints contributed to the death"],
    correctIndex: 1,
    explanation: "PR.9 requires reporting restraint- or seclusion-associated deaths to CMS within 1 business day. The definition is broad: deaths occurring while in restraints, within 24 hours of removal, or within 1 week if restraints contributed.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO PR.9",
    tutor: {
      whyCorrect: "The 1-business-day deadline is a hard federal requirement. Hospitals must have a process to identify, escalate, and report these deaths immediately — not through routine quality processes.",
      whyWrong: { A: "72 hours exceeds the 1 business day limit.", C: "Annual reporting is not an option for restraint-associated deaths.", D: "The 7-day window applies to the definition of which deaths are covered — not to the reporting deadline, which is always 1 business day." },
      operationalContext: "Assign a specific role (Risk Management, CNO) responsibility for 24/7 identification and CMS notification of restraint-associated deaths. Document the notification with time stamp.",
    },
  },
  // ── Infection Control & Medical Records (2) ───────────────────────────────
  {
    id: "dnv_pre_ic_01",
    chapterId: "dnv_ic",
    chapterName: "Infection Control & Medical Records",
    question: "Under NIAHO IC, who must have oversight responsibility for the hospital's infection control program?",
    options: ["The Chief Nursing Officer", "A qualified infection control professional or designated committee with appropriate expertise", "The governing body's quality committee", "The environmental services director"],
    correctIndex: 1,
    explanation: "NIAHO IC requires the infection control program to be overseen by a qualified infection control professional (ICP) or a committee with the appropriate expertise. The program must cover all hospital departments and contracted services.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO IC",
    tutor: {
      whyCorrect: "The ICP or committee is accountable for surveillance, investigation of outbreaks, policy development, staff education, and reporting to leadership and the governing body.",
      whyWrong: { A: "The CNO has accountability for nursing practice but does not hold the infection control program oversight role under NIAHO.", C: "The quality committee receives IC reports but is not the primary oversight body.", D: "Environmental services implements IC practices but does not oversee the program." },
      operationalContext: "Ensure your infection control professional holds CIC (Certified in Infection Control) certification and that their reporting structure includes direct access to senior leadership.",
    },
  },
  {
    id: "dnv_pre_ic_02",
    chapterId: "dnv_ic",
    chapterName: "Infection Control & Medical Records",
    question: "Under NIAHO Medical Records (MR), medical records must be completed within what standard timeframe following patient discharge?",
    options: ["7 days after discharge", "14 days after discharge", "30 days after discharge", "60 days after discharge"],
    correctIndex: 2,
    explanation: "NIAHO MR requires medical records to be completed within 30 days of discharge. This includes the history and physical, operative reports, discharge summary, and any outstanding authentication of verbal orders.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO MR",
    tutor: {
      whyCorrect: "The 30-day completion standard is a widely used benchmark aligned with CMS and TJC standards. NIAHO medical staff bylaws must specify this timeframe and the consequences for non-compliance.",
      whyWrong: { A: "7 days is not the standard completion window; it applies to specific documents like verbal order authentication.", B: "14 days is not the standard.", D: "60 days exceeds the required 30-day standard." },
      operationalContext: "Run a weekly incomplete records report and trigger physician notification at the 15-day and 25-day marks to prevent delinquency.",
    },
  },
  // ── Physical Environment (2) ───────────────────────────────────────────────
  {
    id: "dnv_pre_pe_01",
    chapterId: "dnv_pe",
    chapterName: "Physical Environment",
    question: "Under NIAHO PE.7, an Alternate Equipment Management (AEM) program must include risk assessment for which category of equipment?",
    options: ["All equipment regardless of risk level", "Critical equipment where failure could cause serious injury or death", "Equipment manufactured more than 10 years ago", "Equipment with a history of manufacturer recalls"],
    correctIndex: 1,
    explanation: "PE.7 specifically requires risk assessment for 'critical equipment' in AEM programs — devices where failure could cause serious injury or death. Surveyors focus their review on how the hospital identifies and manages critical equipment.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO PE.7",
    tutor: {
      whyCorrect: "Critical equipment includes life support devices, key resuscitation devices, and critical monitoring equipment. The AEM program must document the risk assessment for why each critical device was placed in the AEM program.",
      whyWrong: { A: "Not all equipment requires individual risk assessment; low-risk equipment can be grouped. Critical equipment requires focused attention.", C: "Age alone does not trigger AEM risk assessment requirements.", D: "Recall history is a consideration but the AEM risk assessment scope is defined by risk level, not recall history." },
      operationalContext: "Create a 'critical equipment' designation field in your equipment inventory. Surveyors will pull your AEM program documentation and look for evidence that critical equipment received individual risk assessment.",
    },
  },
  {
    id: "dnv_pre_pe_02",
    chapterId: "dnv_pe",
    chapterName: "Physical Environment",
    question: "Under NIAHO PE.6, the hospital's emergency preparedness plan must be based on what foundational analysis?",
    options: ["National Incident Management System (NIMS) templates", "Hazard Vulnerability Analysis (HVA)", "State emergency management agency requirements only", "CMS minimum preparedness standards"],
    correctIndex: 1,
    explanation: "PE.6 requires the emergency preparedness program to be based on a Hazard Vulnerability Analysis (HVA). The HVA identifies likely hazards specific to the hospital's geographic location, patient population, and community.",
    xpReward: 12,
    isSwipe: false,
    cmsTag: "NIAHO PE.6",
    tutor: {
      whyCorrect: "The HVA drives the content of the emergency plan — if the HVA does not identify a realistic hazard, the plan need not address it. The HVA must be updated annually or when community conditions change.",
      whyWrong: { A: "NIMS is the national framework for incident management, not the analysis that drives a hospital's specific preparedness plan.", C: "State requirements set a floor but NIAHO requires HVA-based planning.", D: "CMS minimums are baseline requirements; NIAHO's HVA requirement goes further." },
      operationalContext: "Conduct your HVA annually using a validated tool (Kaiser Permanente model is widely used). Document the HVA update date and how findings drove any plan changes.",
    },
  },
];
